language: node_js
node_js:
  - "0.10"

env:
  global:
    - TRAVIS=true
    - secure: "CnG0dxmgyUgCqmcSAEh7JJDDPlDB51S7x6NvOLd+IPgfh51nTZDOKzIzaffS1Sg9EUitFgq5mYvbrxqI5Jp/b5lU102WK2pcTcvR9F4JqYdCaEYRGu6YZ2ZsolF0fcMDPud6xjB6tK6881FiRnAaUHO1zsqgPUJ3vC4/fjZmUTs="
    - secure: "Sc10ucvvxEeKp9kBrxpeBLieyB0CRYgAP3+h4QvzkVm61yR7UvrDdKe6qJ7tP1LorXgAAGgohuSXOWdJHCamgGlt2PjGVFAY/vlDWAvvhvKz3N1XJo388lOxAC8ocBbeaEx6Spycu17QHGgYiSZIKMeTDHw1U2cYXJmpZGSBX7U="

addons:
  sauce_connect: true
